// ESC/POS ticket builders + RawBT silent-print trigger.
//
// Why this exists: window.print() can NEVER be made silent — every browser
// (Chrome included) always shows the OS print dialog by design, no matter
// what JS does. There is no code-only fix for that.
//
// The actual fix is to stop asking the browser to "print a web page" and
// instead hand the printer raw ESC/POS command bytes directly. RawBT
// (installed once on the Android tablet from the Play Store) listens for a
// `rawbt:` link, receives those bytes, and sends them straight to the
// configured printer (WiFi/Bluetooth/USB) with zero dialog.
//
// This file only builds bytes and fires the link — it does not touch the
// printer itself. Nothing here can be tested for a real printed page until
// there's (a) a physical printer and (b) RawBT installed on the tablet.
// From a laptop this can only be checked by inspecting the generated bytes.

// ---- Turkish -> ASCII transliteration -------------------------------------
// Thermal printers vary a lot in which code page they default to, and the
// printer model here hasn't been chosen/bought yet. Rather than guess a code
// page (ESC t n) that might print garbled characters on whatever gets
// purchased, we transliterate Turkish letters to their closest ASCII
// equivalent. Slightly less pretty than "ş" but guaranteed to print
// correctly on literally any ESC/POS printer, regardless of code page.
const TR_MAP: Record<string, string> = {
  'ş': 's', 'Ş': 'S', 'ğ': 'g', 'Ğ': 'G', 'ı': 'i', 'İ': 'I',
  'ö': 'o', 'Ö': 'O', 'ü': 'u', 'Ü': 'U', 'ç': 'c', 'Ç': 'C',
}
function toAscii(str: string): string {
  return String(str ?? '').replace(/[şŞğĞıİöÖüÜçÇ]/g, ch => TR_MAP[ch] ?? ch)
}

// ---- Low-level ESC/POS byte builder ----------------------------------------
class EscPosBuilder {
  private chunks: number[][] = []

  private push(bytes: number[]) { this.chunks.push(bytes) }

  raw(bytes: number[]) { this.push(bytes); return this }

  init() { return this.raw([0x1B, 0x40]) } // ESC @

  alignCenter() { return this.raw([0x1B, 0x61, 0x01]) }
  alignLeft() { return this.raw([0x1B, 0x61, 0x00]) }

  bold(on: boolean) { return this.raw([0x1B, 0x45, on ? 1 : 0]) }

  // Double height + width
  bigText(on: boolean) { return this.raw([0x1D, 0x21, on ? 0x11 : 0x00]) }

  text(str: string) {
    const ascii = toAscii(str)
    const bytes: number[] = []
    for (let i = 0; i < ascii.length; i++) bytes.push(ascii.charCodeAt(i) & 0xff)
    return this.raw(bytes)
  }

  line(str: string = '') { this.text(str); return this.raw([0x0A]) }

  feed(n: number = 1) { return this.raw(Array(n).fill(0x0A)) }

  divider(char: string = '-', width: number = 32) { return this.line(char.repeat(width)) }

  cut() { return this.raw([0x1D, 0x56, 0x00]) } // GS V 0 — full cut

  build(): Uint8Array {
    const flat = ([] as number[]).concat(...this.chunks)
    return new Uint8Array(flat)
  }
}

// ---- Ticket builders --------------------------------------------------------

export function buildKitchenTicketEscPos(tableName: string, orders: any[]): Uint8Array {
  const b = new EscPosBuilder()
  const activeItems = orders.filter((o: any) => o.status === 'pending')
  const rows = activeItems.flatMap((o: any) => (o.items || []).map((it: any) => ({ ...it, note: o.note })))
  const notes = [...new Set(activeItems.filter((o: any) => o.note).map((o: any) => o.note))] as string[]

  b.init()
  b.alignCenter()
  b.bigText(true).bold(true)
  b.line(tableName)
  b.bigText(false).bold(false)
  b.line(new Date().toLocaleString('tr-TR'))
  b.alignLeft()
  b.divider('=')
  b.bold(true)
  for (const it of rows) {
    b.line(`${it.quantity}x  ${toAscii(it.name)}`)
  }
  b.bold(false)
  if (notes.length > 0) {
    b.divider('-')
    b.line(`NOT: ${notes.join(' / ')}`)
  }
  b.divider('=')
  b.feed(3)
  b.cut()
  return b.build()
}

export function buildReceiptEscPos(info: {
  table_name: string, total: number, cash: number, card: number, transfer?: number,
  method: 'cash' | 'card' | 'transfer' | 'mixed' | 'debt', orders: any[],
  discountAmount?: number, discountReason?: string, originalTotal?: number, faturaNo?: number,
}): Uint8Array {
  const b = new EscPosBuilder()
  const fmt = (n: number) => new Intl.NumberFormat('tr-TR', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(n)
  const items = (info.orders || []).flatMap((o: any) => o.items || [])
  const methodLabel = info.method === 'cash' ? 'Nakit' : info.method === 'card' ? 'Kart' : info.method === 'transfer' ? 'Havale/EFT' : info.method === 'debt' ? 'BORC (Veresiye)' : 'Karma (Nakit + Kart)'
  const hasDiscount = (info.discountAmount || 0) > 0

  b.init()
  b.alignCenter()
  b.bigText(true).bold(true)
  b.line('KAHFE LOUNGE')
  b.bigText(false).bold(false)
  b.line(new Date().toLocaleString('tr-TR'))
  if (info.faturaNo) b.line(`FIS NO: ${String(info.faturaNo).padStart(6, '0')}`)
  b.line(`Masa: ${info.table_name}`)
  b.alignLeft()
  b.divider('=')
  for (const it of items) {
    b.line(`${it.quantity}x ${toAscii(it.name)}`)
    b.line(`${' '.repeat(20)}${fmt(it.subtotal)} TL`)
  }
  b.divider('-')
  if (hasDiscount) {
    b.line(`Ara Toplam: ${fmt(info.originalTotal || info.total)} TL`)
    b.line(`Indirim${info.discountReason ? ` (${toAscii(info.discountReason)})` : ''}: -${fmt(info.discountAmount || 0)} TL`)
  }
  b.bold(true).bigText(true)
  b.line(`TOPLAM: ${fmt(info.total)} TL`)
  b.bigText(false).bold(false)
  b.divider('=')
  b.line(`Odeme: ${methodLabel}`)
  if (info.method === 'mixed') {
    b.line(`Nakit: ${fmt(info.cash)} TL`)
    b.line(`Kart: ${fmt(info.card)} TL`)
  }
  b.divider('=')
  b.alignCenter()
  b.line('Bizi tercih ettiginiz icin tesekkurler!')
  b.feed(3)
  b.cut()
  return b.build()
}

// ---- RawBT trigger ----------------------------------------------------------

function bytesToBase64(bytes: Uint8Array): string {
  // Chunked to avoid call-stack overflow from String.fromCharCode(...bigArray)
  const CHUNK = 8000
  let binary = ''
  for (let i = 0; i < bytes.length; i += CHUNK) {
    binary += String.fromCharCode(...bytes.subarray(i, i + CHUNK))
  }
  return btoa(binary)
}

// Sends raw ESC/POS bytes to RawBT (must be installed on the Android device).
// Only works on Android with RawBT installed — on a laptop/desktop this link
// has nothing to open and will just do nothing or show "no app found".
export function printViaRawBT(bytes: Uint8Array) {
  const base64 = bytesToBase64(bytes)
  const url = `rawbt:base64,${base64}`
  window.location.href = url
}
